---
- name: Discover existing file instances
  hosts: all
  gather_facts: false

  vars_files:
    - vars/defaults.yml

  tasks:
    - name: Find files in the directory
      ansible.builtin.find:
        paths: "{{ filespath }}"
      register: discovered_files

    - name: Create File CRs
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: "{{ k8s_cr_version }}"
          kind: File
          metadata:
            name: "{{ item.path | basename | lower | replace('_', '-') | replace('/', '-') | replace('.', '-') }}"
            namespace: "{{ ansible_operator_meta.namespace }}"
            labels:
              file-discovered: "true"
          spec:
            filename: "{{ item.path }}"
            zosendpoint: "{{ zosendpoint }}"
      with_items:
        - "{{ discovered_files.files }}"
      when: k8s_managed is defined and discovered_files.files | length > 0
      delegate_to: localhost
