domain: freemanlatrell
name: file-manager
version: 1.3.0
displayName: File Manager
description: >-
  # File Manager

  The `file-manager` operator allows for the creation, deletion, and discovery of files on a host.
resources:
  - kind: DiscoverFiles
    description: Discover existing Files on the host
    playbook: playbooks/discover.yml
    vars:
      - name: filespath
        displayName: Files Path
        description: >-
          The path to the files to be discovered (ex: /tmp)
        type: string
  - kind: File
    description: Create a File on the host
    playbook: playbooks/create_file.yml
    finalizer: playbooks/delete_file.yml
    vars:
      - name: filename
        displayName: File Name
        description: >-
          The filepath and filename of the file to be created. (ex: /tmp/file.txt)
        type: string
  - kind: FileMessage
    description: Append a message to an existing File instance
    playbook: playbooks/file_message.yml
    vars:
      - name: file_cr_name
        displayName: File
        description: >-
          An existing File instance which will have the specified message appended
        kindReference: File
        type: string
      - name: msg
        displayName: Message
        description: The message that you want to append to the File instance
        type: string
